import { useStore } from "../store";

// The tour guide's script. Audio files are optional: if public/audio/<id>.mp3
// exists (generated by scripts/generate-narration.ts via ElevenLabs) it plays;
// otherwise subtitles alone carry the joke.
export const LINES: Record<string, string> = {
  intro:
    "Welcome to the Museum of Dead Tech. WASD to walk. Touch everything. Break nothing. Let's go.",
  "entry-corridor":
    "Everything in here used to be the coolest thing on the planet. It won't last. It never does.",
  "entry-eniac":
    "The OG computer. Size of a house, dumber than your calculator. Flip the switches. Make it do math.",
  "entry-bombe":
    "This thing broke unbreakable codes and shortened a world war. Press the button. Feel something.",
  "entry-agc":
    "This landed people on the Moon with less memory than one of your selfies. No pressure.",
  "entry-pong":
    "Pong. The big bang of gaming. Every game you've ever loved started with two rectangles.",
  "pong-start": "First to three. Lose and it goes on your permanent record.",
  "pong-win": "You beat 1972. Flex it.",
  "pong-lose": "You lost to two if-statements. Walk it off.",
  "eniac-done": "Boom. Math. In 1945 that took a whole room and six people.",
  "eniac-42": "Forty-two. The answer to everything. Respect.",
  "agc-advance":
    "Verb, noun. Astronauts memorized hundreds of these. You pressed one key. Legend.",
  "agc-1202":
    "Twelve-oh-two alarm. The Moon landing almost got cancelled by a pop-up. Armstrong kept going. Ice cold.",
  "bombe-start": "Drums spinning. Codes breaking. Act natural.",
  "bombe-done":
    "Cracked. Took the pros years. Took you one button. Don't let it go to your head.",
  idle: "You good? The exhibits are right there.",
  "entry-cs":
    "Counter-Strike. Built by Minh Le, an SFU student, between assignments. The GOAT walked these halls. Range is hot.",
  "cs-clear": "All targets down. Minh Le would nod slightly. That's huge.",
  sparky:
    "That's Sparky. He's not an exhibit. He just lives here now. Do not feed him.",
  "pvp-death":
    "You died in a museum. Respawning, because history repeats itself.",
  "pvp-first-kill":
    "You shot another visitor. In 1999 that was a mod. Today it's a Tuesday.",
};

const played = new Set<string>();
const REPEATABLE = new Set([
  "pong-start",
  "pong-win",
  "pong-lose",
  "eniac-done",
  "agc-advance",
  "bombe-start",
  "bombe-done",
  "idle",
  "cs-clear",
  "pvp-death",
]);

let speaking = false;
let currentAudio: HTMLAudioElement | null = null;
let clearTimer: ReturnType<typeof setTimeout> | null = null;

export function say(id: string) {
  const text = LINES[id];
  if (!text) return;
  if (played.has(id) && !REPEATABLE.has(id)) return;
  if (speaking) return; // never interrupt the narrator; drop the line
  played.add(id);
  speaking = true;

  useStore.getState().set({ subtitle: text });
  const duration = 1000 + text.length * 55;

  try {
    currentAudio = new Audio(`/audio/${id}.mp3`);
    currentAudio.play().catch(() => {
      /* no audio file yet — subtitles carry it */
    });
  } catch {
    /* ignore */
  }

  if (clearTimer) clearTimeout(clearTimer);
  clearTimer = setTimeout(() => {
    speaking = false;
    useStore.getState().set({ subtitle: null });
  }, duration);
}
