import { useStore } from "../store";

// The tour guide's script. Audio files are optional: if public/audio/<id>.mp3
// exists (generated by scripts/generate-narration.ts via ElevenLabs) it plays;
// otherwise subtitles alone carry the joke.
export const LINES: Record<string, string> = {
  intro:
    "Welcome to the Museum of Dead Tech. WASD to walk, like your ancestors intended. Try not to touch anything. Actually no, touch everything, that's the point.",
  "entry-corridor":
    "Four rooms, four machines that were each, briefly, the most advanced object on Earth. Now they live here. With you.",
  "entry-eniac":
    "ENIAC, 1945. Thirty tonnes, eighteen thousand vacuum tubes, and less compute than your doorbell. Flip the switches. It loves that.",
  "entry-bombe":
    "The Turing Bombe, 1940s. It broke Enigma and shortened a world war. You may press its button. You will feel important. You shouldn't.",
  "entry-agc":
    "The Apollo Guidance Computer, 1969. It landed humans on the Moon with 4 kilobytes of RAM. Your browser tab rendering me uses roughly forty thousand times that.",
  "entry-pong":
    "Pong, 1972. The entire video game industry, every speedrun, every loot box, traces back to two rectangles and profound boredom.",
  "pong-start":
    "First to three. The AI paddle was written in an afternoon, so losing would be embarrassing. For you.",
  "pong-win":
    "Congratulations. You defeated 1972. The bar was on the floor and you cleared it.",
  "pong-lose":
    "You lost. To two if-statements. The museum keeps a record of this.",
  "eniac-done":
    "Arithmetic complete. In 1945 that cost a room, six operators, and a small city's electricity. You're welcome.",
  "eniac-42":
    "Forty-two. The answer to life, the universe, and everything. ENIAC knew it first, it just couldn't tell anyone.",
  "agc-advance":
    "Verb. Noun. The astronauts memorized hundreds of these. You pressed one key. Equally heroic, really.",
  "agc-1202":
    "Program alarm one-two-oh-two. Executive overflow. Armstrong kept descending. You would have turned the spacecraft off and back on.",
  "bombe-start":
    "Drums spinning. Somewhere, a 1940s codebreaker is doing this with pencil and genuine stakes. Enjoy your version.",
  "bombe-done":
    "Message decrypted. It took Bletchley Park years of secret work. It took you one key press. History thanks you for your service.",
  idle: "You've been standing still for a while. The exhibits are over there. Any of them. Pick one.",
};

const played = new Set<string>();
const REPEATABLE = new Set([
  "pong-start",
  "pong-win",
  "pong-lose",
  "eniac-done",
  "agc-advance",
  "bombe-start",
  "bombe-done",
  "idle",
]);

let speaking = false;
let currentAudio: HTMLAudioElement | null = null;
let clearTimer: ReturnType<typeof setTimeout> | null = null;

export function say(id: string) {
  const text = LINES[id];
  if (!text) return;
  if (played.has(id) && !REPEATABLE.has(id)) return;
  if (speaking) return; // never interrupt the narrator; drop the line
  played.add(id);
  speaking = true;

  useStore.getState().set({ subtitle: text });
  const duration = 1000 + text.length * 55;

  try {
    currentAudio = new Audio(`/audio/${id}.mp3`);
    currentAudio.play().catch(() => {
      /* no audio file yet — subtitles carry it */
    });
  } catch {
    /* ignore */
  }

  if (clearTimer) clearTimeout(clearTimer);
  clearTimer = setTimeout(() => {
    speaking = false;
    useStore.getState().set({ subtitle: null });
  }, duration);
}
